// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8z5GflH7xLhASkpWvIW2v0CP8QIM4UZs',
    appId: '1:774050799627:web:c0f876f565d231b85d270e',
    messagingSenderId: '774050799627',
    projectId: 'resultx-school-app-2026',
    authDomain: 'resultx-school-app-2026.firebaseapp.com',
    storageBucket: 'resultx-school-app-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBXji-OUwsdLiGYiBAnupZ1CDnaGw2hV0',
    appId: '1:774050799627:android:5e5673fe917ccde75d270e',
    messagingSenderId: '774050799627',
    projectId: 'resultx-school-app-2026',
    storageBucket: 'resultx-school-app-2026.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8z5GflH7xLhASkpWvIW2v0CP8QIM4UZs',
    appId: '1:774050799627:web:5f0f0c96687e8a275d270e',
    messagingSenderId: '774050799627',
    projectId: 'resultx-school-app-2026',
    authDomain: 'resultx-school-app-2026.firebaseapp.com',
    storageBucket: 'resultx-school-app-2026.firebasestorage.app',
  );
}
